*** Settings ***
Variables    ../../fixtures/serverest/messages/message_back/msg_globals.yaml
Variables    ../../fixtures/data/user_data.yaml
Variables    ../../fixtures/elements/carts_elements.yaml
Variables    ../../fixtures/elements/product_elements.yaml
Variables    ../../fixtures/elements/user_elements.yaml
Variables    ../../fixtures/elements/login_elements.yaml
*** Variables ***
${s_QUANTITY}    3 